### ISSUE TITLE
Question about `remote_machine_IP`

### ISSUE THREAD

**Issue by dremofly** [SpaceNetLab/StarryNet#1]
I have some questions about parameter `remote_machine_IP`. They are not included in README.

1. Is it OK, if I set `remote_machine_IP` to be `127.0.0.1` when there is no multiple machines. 
2. What does `remote_machine_IP` stand for?
3. If I use multiple machines, how to set their IPs?

Thank you in advance.

**Comment by yangtaodeng** [comment]
Hi, it is ok if you use 127.0.0.1 for remote_machine_IP, and then the emulation will be running on the same controller machine. remote_machine_IP is originally used for running all the emulations on another machine instead of the controller, but still, you can use the same machine.

**Comment by Znculi** [comment]
When I set remote_machine_IP to be 127.0.0.1, an error was raised:
[Errno None] Unable to connect to port 22 on 127.0.0.1
So how can I change the port to running the emulations only use one machine?
