### ISSUE TITLE
Support for Ubuntu 22?

### ISSUE THREAD

**Issue by tkoch96** [SpaceNetLab/StarryNet#14]
I'm trying to run example.py with my execution machine being an AWS VM running Ubuntu 22, and am running into a problem on "docker service create". I don't have a great understanding of docker so I'm sorry if this question doesn't make perfect sense.

When Starrynet tries to create the service, my machine hangs. (Specifically this is in sn_utils:sn_reset_docker_env )

To debug, I tried to run the command myself on my VM, but it still hangs on "overall progress: 0 out of 27 tasks ". When I simultaneously run "docker service ps constellation-test --no-trunc" manually on my VM, I get the error message for all 27 nodes that "no suitable node (unsupported platform on 1 node)".

Am I correct that something in the background is running a check against my OS and seeing that it's not Ubuntu 20 or 18? Would it be very hard to support Ubuntu 22? Is it something that I can fix myself?

I'd appreciate any help!

**Comment by xiex386** [comment]
Did you initialize the Docker swarm? Use the command `docker swarm init` first.

**Comment by tkoch96** [comment]
Yes the above issue is after initializing the swarm

**Comment by xiex386** [comment]
What's your VM architecture? The docker image is built for x86_64.

**Comment by tkoch96** [comment]
Ahhh that's it. Wrong architecture. Sorry for the trouble!

22.04.1-Ubuntu  aarch64 aarch64 aarch64 GNU/Linux
