### ISSUE TITLE
Bug: `cleanup()` in file `starrynet/clean.py` delete all local containers

### ISSUE THREAD

**Issue by dremofly** [SpaceNetLab/StarryNet#2]
In the `cleanup()` function:

```python
with os.popen("docker rm -f $(docker ps -a -q)") as f:
    f.readlines()
```

This command `docker rm -f $(docker ps -a -q)` is set to remove all local containers. 

There is a crucial bug in this function. It inadvertently deletes all of a user's existing containers, not only the ones associated with **StarryNet**. If executed on a server hosting numerous other services, it could result in substantial data loss. This could prove disastrous, especially if some of those services are running critical applications.

**Comment by yangtaodeng** [comment]
Thank you, it's been solved.
